<?php

namespace fibe\Bundle\WWWConfBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfEventRepository extends EntityRepository
{


     public function filtering($params, $currentConf){
    
       $entities = array();
       $qb = $this->createQueryBuilder('confevent');
       $qb     
          ->where('confevent.conference = :conference_id')
          ->setParameter('conference_id', $currentConf->getId());

       if(isset($params['summary'])) {
           $qb
                ->andWhere('confevent.id = :summary')
                ->setParameter('summary', $params['summary'])
            ;
        }

        if(isset($params['location'])) {
            $qb
                ->leftJoin('confevent.location', 'loc')
                ->andWhere('loc.id = :loc')
                ->setParameter('loc', $params['location'])
            ;
        }


        $query = $qb->getQuery();
        return  $query->execute();

    }
}
