<?php

namespace fibe\Bundle\WWWConfBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends EntityRepository
{
  /**
   * getOrderedQueryBuilder
   *
   * @return Object QueryBuilder
   */
  public function getOrderedQueryBuilder()
  {
    $qb = $this->createQueryBuilder('loc');
    $qb->orderBy('loc.name', 'ASC');

    return $qb;
  }

  /**
   * getOrderedQuery
   *
   * @return Object Query
   */
  public function getOrderedQuery()
  {
    $qb = $this->getOrderedQueryBuilder();

    return is_null($qb) ? $qb : $qb->getQuery();
  }

  /**
   * getOrdered
   *
   * @return Object DoctrineCollection
   */
  public function getOrdered()
  {
    $q = $this->getOrderedQuery();

    return is_null($q) ? array() : $q->getResult();
  }

  /**
   * extractQueryBuilder
   *
   * @param array $params
   *
   * @return Object QueryBuilder
   */
  public function extractQueryBuilder($params)
  {
    $qb = $this->getOrderedQueryBuilder();

    if (isset($params['id']))
    {
      $qb
        ->andWhere('loc.id = :id')
        ->setParameter('id', $params['id']);
    }

    if (isset($params['ids']))
    {
      $qb
        ->andWhere($qb->expr()->in('loc.id', $params['ids']));
    }

    if (isset($params['name']))
    {
      $qb
        ->andWhere('loc.title = :name')
        ->setParameter('name', $params['name']);
    }

    if (isset($params['conference_id']))
    {
      $qb
        ->andWhere('loc.conference = :conference_id')
        ->setParameter('conference_id', $params['conference_id']);
    }

    return $qb;
  }

  /**
   * extractQuery
   *
   * @param array $params
   *
   * @return Object Query
   */
  public function extractQuery($params)
  {
    $qb = $this->extractQueryBuilder($params);

    return is_null($qb) ? $qb : $qb->getQuery();
  }

  /**
   * extract
   *
   * @param array $params
   *
   * @return Object DoctrineCollection
   */
  public function extract($params)
  {
    $q = $this->extractQuery($params);

    return is_null($q) ? array() : $q->getResult();
  }

  /**
   * filtering function
   *
   * @param $params
   * @param $currentConf
   *
   * @return mixed
   */
  public function filtering($params, $currentConf)
  {
    $qb = $this->createQueryBuilder('org');
    $qb
      ->where('org.conference = :conference_id')
      ->setParameter('conference_id', $currentConf->getId());

    if (isset($params['id']))
    {
      $qb
        ->andWhere('org.id = :id')
        ->setParameter('id', $params['id']);
    }

    if (isset($params['member']))
    {
      $qb
        ->leftJoin('org.members', 'pers')
        ->andWhere('pers.id = :person_id')
        ->setParameter('person_id', $params['member']);
    }

    if (isset($params['country']))
    {
      $qb
        ->andWhere($qb->expr()->like('org.country', $qb->expr()->literal('%' . $params['country'] . '%')));

    }

    $query = $qb->getQuery();

    return $query->execute();

  }
}
