<?php

  namespace fibe\Bundle\WWWConfBundle\Repository;

  use Doctrine\ORM\EntityRepository;

  /**
   * WwwConfRepository
   *
   * This class was generated by the Doctrine ORM. Add your own custom
   * repository methods below.
   *
   */
  class WwwConfRepository extends EntityRepository
  {
    /**
     * getOrderedQueryBuilder
     *
     * @return Object QueryBuilder
     */
    public function getOrderedQueryBuilder()
    {
      $qb = $this->createQueryBuilder('conf');
      $qb->orderBy('conf.mainConfEvent.startAt', 'DESC');

      return $qb;
    }

    /**
     * getOrderedQuery
     *
     * @return Object Query
     */
    public function getOrderedQuery()
    {
      $qb = $this->getOrderedQueryBuilder();

      return is_null($qb) ? $qb : $qb->getQuery();
    }

    /**
     * getOrdered
     *
     * @return Object DoctrineCollection
     */
    public function getOrdered()
    {
      $q = $this->getOrderedQuery();

      return is_null($q) ? array() : $q->getResult();
    }


    /**
     * @TODO comment
     *
     * @param $name
     *
     * @return mixed
     */
    public function findByName($name)
    {

      $qb = $this->createQueryBuilder('conf');

      $qb
        ->leftJoin('conf.mainConfEvent', 'ev')
        ->where($qb->expr()->like('ev.summary', $qb->expr()->literal('%' . $name . '%')));

      $query = $qb->getQuery();
      return $query->execute();
    }

    /**
     * @TODO comment
     *
     * @return mixed
     */
    public function findOrderByDate()
    {

      $qb = $this->createQueryBuilder('conf');

      $qb
        ->leftJoin('conf.mainConfEvent', 'ev')
        ->orderBy('ev.startAt', 'DESC');

      $query = $qb->getQuery();
      return $query->execute();
    }

  }
