jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        fibe\SecurityBundle\Entity\User: sha512

    providers:
        main:
            entity: { class: fibe\SecurityBundle\Entity\User, property: username }

    acl:
        connection: default

#        in_memory:
#            memory:
#                users:
#                    #define here the user password of the "admin" account
#                    admin: { password: wwwconfTER, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


        main_login:
            # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   ^/login$
            anonymous: true # On autorise les anonymes sur ce pare-feu

        main_homepage:
            # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   ^/$
            anonymous: true # On autorise les anonymes sur ce pare-feu

        public_apps:
            # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   ^/apps/
            anonymous: true # On autorise les anonymes sur ce pare-feu

        api:
            pattern:   ^/api/
            anonymous: true 
        data:
            pattern:   ^/data/
            anonymous: true 
        register:
            pattern:   ^/user/register/
            anonymous: true 


        main:
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            pattern:   ^/
            anonymous: false
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
                # success_handler: fibe_security.select_conference_success_handler
            logout:
                path:   logout
                target: /login

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

